package capabilities

// Builtins returns capabilities that are always available in rivet,
// regardless of project config. Vaulty and recon capabilities run
// in-process via their embedded dependencies.
func Builtins() []Capability {
	return []Capability{
		// --- Recon: repo intelligence ---
		{
			Name:        "recon.overview",
			Kind:        KindTool,
			Description: "Structured repo summary — languages, frameworks, structure, entrypoints. No args needed.",
			Command:     []string{"recon", "overview"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required",
		},
		{
			Name:        "recon.related",
			Kind:        KindTool,
			Description: "Find files related to a FILE PATH — imports, co-change, naming, test pairs. Args: [\"path/to/file.ex\"]",
			Command:     []string{"recon", "related"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A single file path (NOT a directory). Example: [\"lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "recon.tests",
			Kind:        KindTool,
			Description: "Find test files relevant to a source file or directory. Args: [\"path/to/file.ex\"]",
			Command:     []string{"recon", "tests"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A file or directory path. Example: [\"lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "recon.symbols",
			Kind:        KindTool,
			Description: "Search symbols or list symbols in a file. Args: [\"query\"] to search, [\"file:path/to/file.ex\"] to list a file's symbols",
			Command:     []string{"recon", "symbols"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A search query OR \"file:path\" to list symbols in a specific file. Examples: [\"send_sms\"], [\"file:lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "recon.changes",
			Kind:        KindTool,
			Description: "Recent git change summary — commits, affected files, areas. Args: [\"--since\", \"30d\"] for custom range (default: 7d)",
			Command:     []string{"recon", "changes"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "Optional: [\"--since\", \"30d\"] to set time range. Default is 7 days.",
		},
		{
			Name:        "recon.search",
			Kind:        KindTool,
			Description: "Search across symbols, file paths, and file content. START HERE to find files. Args: [\"keyword\"]",
			Command:     []string{"recon", "search"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A search keyword or phrase. Example: [\"billing\"], [\"twilio\"], [\"sms provider\"]",
		},
		{
			Name:        "recon.context",
			Kind:        KindTool,
			Description: "File metrics — preview, fan-in/fan-out, churn, hotspot score. Args: [\"path/to/file.ex\"] (must be a FILE, not directory)",
			Command:     []string{"recon", "context"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A single file path (NOT a directory). Example: [\"lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "recon.hotspots",
			Kind:        KindTool,
			Description: "Top files ranked by hotspot score (fan-in * churn) — riskiest to change. No args needed.",
			Command:     []string{"recon", "hotspots"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required",
		},
		{
			Name:        "recon.grep",
			Kind:        KindTool,
			Description: "Enriched grep — results grouped by file with definition/reference/test/comment classification, fan-in, and hotspot scores. Returns a summary header + file groups. Use --type to filter. Args: [\"pattern\"] or [\"pattern\", \"--type\", \"definition\"]",
			Command:     []string{"recon", "grep"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A search pattern, optionally with --type=definition|reference|test|comment to filter. Examples: [\"SMS.send\"], [\"Accounts.\", \"--type\", \"definition\"], [\"register_user\", \"--type\", \"reference\"]",
		},
		{
			Name:        "recon.refresh",
			Kind:        KindTool,
			Description: "Incremental cache update — re-scans changed files only. No args needed.",
			Command:     []string{"recon", "refresh"},
			Output:      "text",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required",
		},
		// --- Vaulty: secrets proxy ---
		{
			Name:        "vaulty.list",
			Kind:        KindTool,
			Description: "List stored secrets (names and policies, never values)",
			Command:     []string{"vaulty", "list"},
			Output:      "text",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
		},
		{
			Name:        "vaulty.set",
			Kind:        KindTool,
			Description: "Add or update a secret in the vault",
			Command:     []string{"vaulty", "set"},
			Output:      "text",
			Safety:      SafetyLevelGuarded,
			Builtin:     true,
		},
		{
			Name:        "vaulty.remove",
			Kind:        KindTool,
			Description: "Remove a secret from the vault",
			Command:     []string{"vaulty", "remove"},
			Output:      "text",
			Safety:      SafetyLevelDangerous,
			Builtin:     true,
		},
		{
			Name:        "vaulty.exec",
			Kind:        KindTool,
			Description: "Execute a command with secrets injected into environment",
			Command:     []string{"vaulty", "exec"},
			Output:      "text",
			Safety:      SafetyLevelGuarded,
			Builtin:     true,
		},
		{
			Name:        "vaulty.proxy",
			Kind:        KindTool,
			Description: "Make an authenticated HTTP request through Vaulty",
			Command:     []string{"vaulty", "proxy"},
			Output:      "json",
			Safety:      SafetyLevelGuarded,
			Builtin:     true,
		},
		{
			Name:        "vaulty.export-env",
			Kind:        KindTool,
			Description: "Export secrets as environment variables",
			Command:     []string{"vaulty", "export-env"},
			Output:      "text",
			Safety:      SafetyLevelGuarded,
			Builtin:     true,
		},
	}
}
