package capabilities

// Builtins returns capabilities that are always available in rivet,
// regardless of project config. Vaulty and recon capabilities run
// in-process via their embedded dependencies.
func Builtins() []Capability {
	return []Capability{
		// --- Recon: repo intelligence ---
		{
			Name:        "recon.overview",
			Kind:        KindTool,
			Description: "Structured repo summary — languages, frameworks, structure, entrypoints. No args needed.",
			Command:     []string{"recon", "overview"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required",
		},
		{
			Name:        "recon.related",
			Kind:        KindTool,
			Description: "Find files related to a FILE PATH — imports, co-change, naming, test pairs. Args: [\"path/to/file.ex\"]",
			Command:     []string{"recon", "related"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A single file path (NOT a directory). Example: [\"lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "recon.tests",
			Kind:        KindTool,
			Description: "Find test files relevant to a source file or directory. Args: [\"path/to/file.ex\"]",
			Command:     []string{"recon", "tests"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A file or directory path. Example: [\"lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "recon.symbols",
			Kind:        KindTool,
			Description: "Search symbols or list symbols in a file. Args: [\"query\"] to search, [\"file:path/to/file.ex\"] to list a file's symbols",
			Command:     []string{"recon", "symbols"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A search query OR \"file:path\" to list symbols in a specific file. Examples: [\"send_sms\"], [\"file:lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "recon.callers",
			Kind:        KindTool,
			Description: "Find where a symbol is defined and every call site that references it. Args: [\"SymbolName\"]",
			Command:     []string{"recon", "callers"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A symbol (function/method/type) name to find callers of. Example: [\"NewServer\"]",
		},
		{
			Name:        "recon.changes",
			Kind:        KindTool,
			Description: "Recent git change summary — commits, affected files, areas. Args: [\"--since\", \"30d\"] for custom range (default: 7d)",
			Command:     []string{"recon", "changes"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "Optional: [\"--since\", \"30d\"] to set time range. Default is 7 days.",
		},
		{
			Name:        "recon.search",
			Kind:        KindTool,
			Description: "Search across symbols, file paths, and file content. START HERE to find files. Args: [\"keyword\"]",
			Command:     []string{"recon", "search"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A search keyword or phrase. Example: [\"billing\"], [\"twilio\"], [\"sms provider\"]",
		},
		{
			Name:        "recon.context",
			Kind:        KindTool,
			Description: "File metrics — preview, fan-in/fan-out, churn, hotspot score. Args: [\"path/to/file.ex\"] (must be a FILE, not directory)",
			Command:     []string{"recon", "context"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A single file path (NOT a directory). Example: [\"lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "recon.hotspots",
			Kind:        KindTool,
			Description: "Top files ranked by hotspot score (fan-in * churn) — riskiest to change. No args needed.",
			Command:     []string{"recon", "hotspots"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required",
		},
		{
			Name:        "recon.grep",
			Kind:        KindTool,
			Description: "Enriched grep — results grouped by file with definition/reference/test/comment classification, fan-in, and hotspot scores. Returns a summary header + file groups. Use --type to filter. Args: [\"pattern\"] or [\"pattern\", \"--type\", \"definition\"]",
			Command:     []string{"recon", "grep"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "A search pattern, optionally with --type=definition|reference|test|comment to filter. Examples: [\"SMS.send\"], [\"Accounts.\", \"--type\", \"definition\"], [\"register_user\", \"--type\", \"reference\"]",
		},
		{
			Name:        "recon.refresh",
			Kind:        KindTool,
			Description: "Incremental cache update — re-scans changed files only. No args needed.",
			Command:     []string{"recon", "refresh"},
			Output:      "text",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required",
		},
		// --- Schema: database intelligence ---
		{
			Name:        "schema.overview",
			Kind:        KindTool,
			Description: "Summary of configured databases and migration status. No args needed.",
			Command:     []string{"schema", "overview"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required",
		},
		{
			Name:        "schema.tables",
			Kind:        KindTool,
			Description: "List every table in the target database with row estimates and sizes. Use --db to pick a non-default connection. Args: [\"--db\", \"prod\"]",
			Command:     []string{"schema", "tables"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "Optional: [\"--db\", \"<name>\"] to target a non-default database",
		},
		{
			Name:        "schema.describe",
			Kind:        KindTool,
			Description: "Show columns, indexes, and foreign keys for a single table. Args: [\"users\"] or [\"public.orders\"]",
			Command:     []string{"schema", "describe"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "Table name (optionally schema-qualified). Example: [\"orders\"], [\"public.users\"]",
		},
		{
			Name:        "schema.indexes-unused",
			Kind:        KindTool,
			Description: "Indexes with zero reads (pure write cost) — drop candidates. Read from pg_stat_user_indexes (Postgres) or sys.dm_db_index_usage_stats (MSSQL).",
			Command:     []string{"schema", "indexes", "unused"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required. Optional: [\"--db\", \"<name>\"]",
		},
		{
			Name:        "schema.indexes-redundant",
			Kind:        KindTool,
			Description: "Indexes whose columns are fully covered by another index on the same table — classic redundancy.",
			Command:     []string{"schema", "indexes", "redundant"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required. Optional: [\"--db\", \"<name>\"]",
		},
		{
			Name:        "schema.indexes-missing",
			Kind:        KindTool,
			Description: "Indexes the engine + code analysis suggest adding. Combines MSSQL missing-index DMVs / pg_qualstats with WHERE/JOIN/ORDER BY columns extracted from Dapper, Go, Python, and Node source.",
			Command:     []string{"schema", "indexes", "missing"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required. Optional: [\"--db\", \"<name>\"]",
		},
		{
			Name:        "schema.indexes-list",
			Kind:        KindTool,
			Description: "List every index in the target database with columns, uniqueness, and size.",
			Command:     []string{"schema", "indexes", "list"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required. Optional: [\"--db\", \"<name>\"]",
		},
		{
			Name:        "schema.queries-extracted",
			Kind:        KindTool,
			Description: "SQL statements found in application source (Dapper/C#, Go database/sql and sqlx, Python psycopg/SQLAlchemy, Node pg/knex/prisma).",
			Command:     []string{"schema", "queries", "extracted"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required",
		},
		{
			Name:        "schema.queries-slow",
			Kind:        KindTool,
			Description: "Top expensive queries from the engine log (pg_stat_statements / sys.dm_exec_query_stats).",
			Command:     []string{"schema", "queries", "slow"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "Optional: [\"--limit\", \"50\"] to change the cap",
		},
		{
			Name:        "schema.coverage",
			Kind:        KindTool,
			Description: "Per-table map of which application queries hit the table and whether their predicates are covered by an existing index.",
			Command:     []string{"schema", "coverage"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required. Optional: [\"--db\", \"<name>\"]",
		},
		{
			Name:        "schema.migrations",
			Kind:        KindTool,
			Description: "Reconstruct a schema statically from SQL migration files — no DB connection needed.",
			Command:     []string{"schema", "migrations"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required",
		},
		{
			Name:        "schema.refresh",
			Kind:        KindTool,
			Description: "Re-read catalog and stats from every configured database into the local snapshot cache.",
			Command:     []string{"schema", "refresh"},
			Output:      "text",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required. Optional: [\"--db\", \"<name>\"] to refresh only one",
		},
		// --- Witness: test selector ---
		{
			Name:        "witness.select",
			Kind:        KindTool,
			Description: "Select tests to run based on changed files. Uses dependency graph, co-change history, and hotspot scoring. No args = use git diff. Args: [\"path/to/changed.ex\"] or [\"path/a.ex\", \"path/b.ex\"]",
			Command:     []string{"witness", "select"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "Changed file paths, or no args to detect from git diff. Example: [\"lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "witness.run",
			Kind:        KindTool,
			Description: "Get the test-runner command for the changed files — returns a command STRING (e.g. 'go test ./pkg/...' or 'mix test path1 path2') for you to execute yourself with your shell/Bash tool. This does NOT run the tests; it only tells you the right command to run. No args = use git diff. Args: [\"path/to/changed.ex\"]",
			Command:     []string{"witness", "select", "--format", "exec"},
			Output:      "text",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "Changed file paths, or no args to detect from git diff. Example: [\"lib/my_app/accounts.ex\"]",
		},
		{
			Name:        "witness.staged",
			Kind:        KindTool,
			Description: "Select tests for staged git changes (pre-commit). Uses git diff --staged to detect files, then scores tests by dependency graph, co-change, and hotspots. No args needed.",
			Command:     []string{"witness", "select", "--staged"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			ArgsHint:    "No arguments required — uses git diff --staged automatically",
		},
		{
			Name:        "witness.since",
			Kind:        KindTool,
			Description: "Select tests for all changes since a git ref (branch point, tag, or commit). Useful for PR review — finds every test affected by the branch. Args: [\"main\"] or [\"v1.2.0\"] or [\"abc123\"]",
			Command:     []string{"witness", "select"},
			Output:      "json",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
			Params: []Param{
				{Name: "ref", Type: "string", Required: true, Description: "Git ref to compare against (branch, tag, or commit SHA)", Flag: "--since"},
			},
		},
		// --- Vaulty: secrets proxy ---
		{
			Name:        "vaulty.list",
			Kind:        KindTool,
			Description: "List stored secrets (names and policies, never values)",
			Command:     []string{"vaulty", "list"},
			Output:      "text",
			Safety:      SafetyLevelSafe,
			Builtin:     true,
		},
		{
			Name:        "vaulty.set",
			Kind:        KindTool,
			Description: "Add or update a secret in the vault",
			Command:     []string{"vaulty", "set"},
			Output:      "text",
			Safety:      SafetyLevelGuarded,
			Builtin:     true,
		},
		{
			Name:        "vaulty.remove",
			Kind:        KindTool,
			Description: "Remove a secret from the vault",
			Command:     []string{"vaulty", "remove"},
			Output:      "text",
			Safety:      SafetyLevelDangerous,
			Builtin:     true,
		},
		{
			Name:        "vaulty.exec",
			Kind:        KindTool,
			Description: "Execute a command with secrets injected into environment",
			Command:     []string{"vaulty", "exec"},
			Output:      "text",
			Safety:      SafetyLevelGuarded,
			Builtin:     true,
		},
		{
			Name:        "vaulty.proxy",
			Kind:        KindTool,
			Description: "Make an authenticated HTTP request through Vaulty",
			Command:     []string{"vaulty", "proxy"},
			Output:      "json",
			Safety:      SafetyLevelGuarded,
			Builtin:     true,
		},
		{
			Name:        "vaulty.export-env",
			Kind:        KindTool,
			Description: "Export secrets as environment variables",
			Command:     []string{"vaulty", "export-env"},
			Output:      "text",
			Safety:      SafetyLevelGuarded,
			Builtin:     true,
		},
	}
}
