package sync

import (
	"fmt"
	"os"
	"strings"

	"github.com/djtouchette/rivet/internal/capabilities"
	rivetctx "github.com/djtouchette/rivet/internal/context"
)

const (
	markerStart = "<!-- rivet:start -->"
	markerEnd   = "<!-- rivet:end -->"
)

// GenerateClaudeMD produces the rivet-managed CLAUDE.md section content.
func GenerateClaudeMD(caps []capabilities.Capability, docs []*rivetctx.Document) string {
	var b strings.Builder

	b.WriteString(markerStart)
	b.WriteString("\n")
	b.WriteString("<!-- DO NOT EDIT between rivet markers — regenerated by 'rivet sync' -->\n\n")
	b.WriteString("# Rivet — Project Capabilities\n\n")

	// Group capabilities by safety level.
	writeCaps(&b, caps)

	// Context summary.
	writeContext(&b, docs)

	// MCP usage rules.
	b.WriteString("## Rivet Rules\n\n")
	b.WriteString("Rivet is available as an MCP server. **Always check context docs before reaching for recon tools.**\n\n")

	// Tiered workflow.
	b.WriteString("### Understand tasks (explain, audit, review, investigate)\n\n")
	b.WriteString("Context docs are the first source of truth. Most questions are already answered there.\n\n")
	b.WriteString("1. **`rivet.context-recommend`** with your task description\n")
	b.WriteString("2. **`rivet.context-show`** to read the recommended docs\n")
	b.WriteString("3. **Read the source code** if the context doc doesn't fully answer the question\n")
	b.WriteString("4. Only use `recon.grep` / `recon.search` if you don't know where to look\n")
	b.WriteString("5. **`rivet.learn`** — you MUST record any non-obvious finding. This is not optional.\n\n")

	b.WriteString("### Change tasks (fix, add, refactor)\n\n")
	b.WriteString("Changes require understanding blast radius. Use the full recon sweep.\n\n")
	b.WriteString("1. **`rivet.context-recommend`** → **`rivet.context-show`** — read domain context first\n")
	b.WriteString("2. **`recon.related`** on the file you plan to change — know what depends on it\n")
	b.WriteString("3. **`recon.hotspots`** if refactoring — know which files are riskiest\n")
	b.WriteString("4. **`recon.grep`** to trace callers and assess impact. Use `--type definition` to find definitions only. Use plain Grep for simple targeted lookups.\n")
	b.WriteString("5. **`recon.context`** on high-fan-in files to check risk metrics before modifying them\n")
	b.WriteString("6. **`rivet.learn`** — you MUST record any non-obvious finding. This is not optional.\n\n")

	// Tool reference.
	b.WriteString("### Tool reference\n\n")
	b.WriteString("| Tool | Args | Example |\n")
	b.WriteString("|------|------|---------|\n")
	b.WriteString("| `rivet.context-recommend` | `{\"query\": \"...\"}` | `{\"query\": \"how does billing work\"}` |\n")
	b.WriteString("| `rivet.context-show` | `{\"name\": \"...\"}` | `{\"name\": \"billing\"}` |\n")
	b.WriteString("| `rivet.learn` | `{\"doc\": \"...\", \"learning\": \"...\"}` | `{\"doc\": \"billing\", \"learning\": \"AddTax does a 3-table join on every insert\"}` |\n")
	b.WriteString("| `recon.grep` | `[\"pattern\"]` or `[\"pattern\", \"--type\", \"definition\"]` | `[\"SMS.send\"]`, `[\"Accounts.\", \"--type\", \"definition\"]` |\n")
	b.WriteString("| `recon.search` | `[\"keyword\"]` | `[\"billing\"]`, `[\"twilio\"]` |\n")
	b.WriteString("| `recon.symbols` | `[\"query\"]` or `[\"file:path/to/file.ex\"]` | `[\"file:lib/app/accounts.ex\"]` |\n")
	b.WriteString("| `recon.related` | `[\"path/to/file.ex\"]` | `[\"lib/app/notifications/sms.ex\"]` |\n")
	b.WriteString("| `recon.context` | `[\"path/to/file.ex\"]` | `[\"lib/app/accounts.ex\"]` |\n")
	b.WriteString("| `recon.hotspots` | (no args) | Shows riskiest files to change |\n\n")
	b.WriteString("**Important**: `recon.related`, `recon.context`, and `recon.symbols file:` require a **file path**, not a directory. Use `recon.search` first to find the right files.\n\n")

	b.WriteString(markerEnd)
	return b.String()
}

func writeCaps(b *strings.Builder, caps []capabilities.Capability) {
	if len(caps) == 0 {
		b.WriteString("No capabilities registered.\n\n")
		return
	}

	safe := filterBySafety(caps, capabilities.SafetyLevelSafe)
	guarded := filterBySafety(caps, capabilities.SafetyLevelGuarded)
	dangerous := filterBySafety(caps, capabilities.SafetyLevelDangerous)

	if len(safe) > 0 {
		b.WriteString("### Safe (read-only, auto-run)\n\n")
		writeCapTable(b, safe)
	}
	if len(guarded) > 0 {
		b.WriteString("### Guarded (may require checks)\n\n")
		writeCapTable(b, guarded)
	}
	if len(dangerous) > 0 {
		b.WriteString("### Dangerous (requires approval)\n\n")
		writeCapTable(b, dangerous)
	}
}

func writeCapTable(b *strings.Builder, caps []capabilities.Capability) {
	b.WriteString("| Capability | Kind | Description |\n")
	b.WriteString("|---|---|---|\n")
	for _, c := range caps {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", c.Name, c.Kind, c.Description))
	}
	b.WriteString("\n")
}

func writeContext(b *strings.Builder, docs []*rivetctx.Document) {
	if len(docs) == 0 {
		return
	}

	b.WriteString("## Context Documents\n\n")
	b.WriteString("Structured context is available via MCP resources or `rivet context show <name>`.\n\n")

	domains := filterByKind(docs, rivetctx.KindDomain)
	modules := filterByKind(docs, rivetctx.KindModule)
	paradigms := filterByKind(docs, rivetctx.KindParadigm)

	if len(domains) > 0 {
		b.WriteString("**Domains:** ")
		b.WriteString(docNames(domains))
		b.WriteString("\n\n")
	}
	if len(modules) > 0 {
		b.WriteString("**Modules:** ")
		b.WriteString(docNames(modules))
		b.WriteString("\n\n")
	}
	if len(paradigms) > 0 {
		b.WriteString("**Paradigms:** ")
		b.WriteString(docNames(paradigms))
		b.WriteString("\n\n")
	}
}

func docNames(docs []*rivetctx.Document) string {
	names := make([]string, len(docs))
	for i, d := range docs {
		names[i] = d.Name
	}
	return strings.Join(names, ", ")
}

func filterBySafety(caps []capabilities.Capability, level capabilities.SafetyLevel) []capabilities.Capability {
	var out []capabilities.Capability
	for _, c := range caps {
		if c.Safety == level {
			out = append(out, c)
		}
	}
	return out
}

func filterByKind(docs []*rivetctx.Document, kind rivetctx.Kind) []*rivetctx.Document {
	var out []*rivetctx.Document
	for _, d := range docs {
		if d.Kind == kind {
			out = append(out, d)
		}
	}
	return out
}

// WriteClaudeMD writes the rivet section into the CLAUDE.md file at the given path.
// If the file exists, only the content between rivet markers is replaced.
// If the file doesn't exist, it is created with the rivet section at the top.
func WriteClaudeMD(path string, section string) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			// New file: rivet section first, then a blank area for user content.
			content := section + "\n"
			return os.WriteFile(path, []byte(content), 0644)
		}
		return fmt.Errorf("reading %s: %w", path, err)
	}

	updated := replaceSection(string(existing), section)
	return os.WriteFile(path, []byte(updated), 0644)
}

// replaceSection replaces the content between rivet markers, or appends if markers not found.
func replaceSection(content, section string) string {
	startIdx := strings.Index(content, markerStart)
	endIdx := strings.Index(content, markerEnd)

	if startIdx >= 0 && endIdx >= 0 {
		endIdx += len(markerEnd)
		// Consume one trailing newline after the end marker if present.
		if endIdx < len(content) && content[endIdx] == '\n' {
			endIdx++
		}
		return content[:startIdx] + section + "\n" + content[endIdx:]
	}

	// No markers found — prepend the rivet section.
	return section + "\n\n" + content
}
